// Bundles the source tree into a single text file that Figma Make can ingest.
// Run with: npm run pack
//
// What's included (in order):
//   1. Repo-level config: package.json, vite.config.ts, tsconfig*.json,
//      index.html, vercel.json, postcss.config.mjs, README.md
//   2. Every text file under src/ (skipping binary assets — png, jpg, woff, ttf, otf, eot)
//
// Each file is prefixed with a header line so the destination tool knows
// where the content belongs. Output lands in `proto-bundle.txt`.

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT = join(ROOT, 'proto-bundle.txt');

const ROOT_FILES = [
  'package.json',
  'tsconfig.json',
  'tsconfig.app.json',
  'tsconfig.node.json',
  'vite.config.ts',
  'index.html',
  'vercel.json',
  'postcss.config.mjs',
  'README.md',
];

const SKIP_EXT = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg',
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.ico', '.icns', '.mp4', '.webm', '.zip',
]);

const SKIP_DIR = new Set(['node_modules', 'dist', '.git', '.vercel', '.next', 'build']);

function walk(dir, out) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIR.has(entry)) continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      walk(full, out);
    } else if (!SKIP_EXT.has(extname(entry).toLowerCase())) {
      out.push(full);
    }
  }
}

function readSafe(path) {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

const chunks = [];

chunks.push(
  `// proto-bundle.txt`,
  `// Generated by scripts/pack.mjs on ${new Date().toISOString()}`,
  `// Source: ${ROOT}`,
  `// Drop this whole file into Figma Make to recreate the prototype.`,
  ``,
);

for (const name of ROOT_FILES) {
  const path = join(ROOT, name);
  if (!existsSync(path)) continue;
  const body = readSafe(path);
  if (body == null) continue;
  chunks.push(`// === ${name} ===`, body, '');
}

const srcDir = join(ROOT, 'src');
const srcFiles = [];
if (existsSync(srcDir)) walk(srcDir, srcFiles);
srcFiles.sort();

for (const path of srcFiles) {
  const body = readSafe(path);
  if (body == null) continue;
  chunks.push(`// === ${relative(ROOT, path)} ===`, body, '');
}

writeFileSync(OUT, chunks.join('\n'), 'utf8');

const bytes = chunks.join('\n').length;
const fileCount = ROOT_FILES.filter((n) => existsSync(join(ROOT, n))).length + srcFiles.length;
console.log(`Packed ${fileCount} files → proto-bundle.txt (${(bytes / 1024).toFixed(1)} KB)`);
